# Image compression using K-Means algorithm. 
K-Means clustering is a form of unsupervised machine learning. Through this notebook I will use K-Means clustering to
perform image compression: Pixels in an image will be grouped by their similarity in order to reduce the total number of
colors within that image.


In [1]:
from skimage import io
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as image

## Load Image
Image will be loaded and reshaped in order to each row represent a pixel and the three columns represent the Red, Green
and Blue values.

In [2]:
input_image = io.imread('bird_small.png')
reshaped_image = (input_image / 255.0).reshape(-1, 3)
reshaped_image

Array([[0.85882353, 0.70588235, 0.40392157],
       [0.90196078, 0.7254902 , 0.45490196],
       [0.88627451, 0.72941176, 0.43137255],
       ...,
       [0.25490196, 0.16862745, 0.15294118],
       [0.22745098, 0.14509804, 0.14901961],
       [0.20392157, 0.15294118, 0.13333333]])

## Running K-Means
First of all K-Means will be fitted on resized image. The number of clusters is the desired numbers of colors.

In [3]:
k_colors = KMeans(n_clusters=16).fit(reshaped_image)

Assign colors to pixels based on their cluster center each row in k_colors.cluster_centers_ represents the RGB value of 
a cluster centroid k_colors.labels_ contains the cluster that a pixel is assigned to the following assigns every pixel 
the color of the centroid it is assigned to.

In [4]:
image_16 = k_colors.cluster_centers_[k_colors.labels_]
image_16

array([[0.86672256, 0.71873224, 0.45969214],
       [0.86672256, 0.71873224, 0.45969214],
       [0.86672256, 0.71873224, 0.45969214],
       ...,
       [0.15640251, 0.16011074, 0.15230356],
       [0.15640251, 0.16011074, 0.15230356],
       [0.15640251, 0.16011074, 0.15230356]])

Now image is reshaped to original size to save it

In [5]:
image_16 = np.reshape(image_16, input_image.shape)
image_16

array([[[0.86672256, 0.71873224, 0.45969214],
        [0.86672256, 0.71873224, 0.45969214],
        [0.86672256, 0.71873224, 0.45969214],
        ...,
        [0.08347191, 0.09036018, 0.08007494],
        [0.08347191, 0.09036018, 0.08007494],
        [0.08347191, 0.09036018, 0.08007494]],

       [[0.86672256, 0.71873224, 0.45969214],
        [0.86672256, 0.71873224, 0.45969214],
        [0.86672256, 0.71873224, 0.45969214],
        ...,
        [0.08347191, 0.09036018, 0.08007494],
        [0.08347191, 0.09036018, 0.08007494],
        [0.08347191, 0.09036018, 0.08007494]],

       [[0.86672256, 0.71873224, 0.45969214],
        [0.86672256, 0.71873224, 0.45969214],
        [0.86672256, 0.71873224, 0.45969214],
        ...,
        [0.08347191, 0.09036018, 0.08007494],
        [0.08347191, 0.09036018, 0.08007494],
        [0.08347191, 0.09036018, 0.08007494]],

       ...,

       [[0.08347191, 0.09036018, 0.08007494],
        [0.08347191, 0.09036018, 0.08007494],
        [0.08347191, 0

In [7]:
image.imsave('image_16.png', image_16)
